### ISSUE TITLE
Refreshments ability doesn't apply healing

### ISSUE THREAD

**Issue by BlackCapCoder** [xeuorux/Pokemon-Tectonic#32]
The refreshments ability doesn't actually do any healing!

The amount to be healed is correctly calculated, but it is never applied because `aiCheck` has been hard-coded to `true` here:

https://github.com/xeuorux/Pokemon-Tectonic/blob/0b92977da7bb7e96813ebf5649d4c35de204dea0/Plugins/Tectonic%20Battle/Abilities/AbilityHandlerHelpers.rb#L146

rather than passing along the `aiCheck` parameter we get at the top of the function.

```ruby
healingScore = lowestIdBattler.applyFractionalHealing(healingFraction, aiCheck: aiCheck)
```

**Comment by xeuorux** [comment]
Sorry this was already fixed a while back, i barely ever check the github. We pretty much only take bug reports on our discord server.
